// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 7267 (Chief Ukorz Sandscalp), 15 anchors over 238yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_7267()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 7267,
        {
            { 1880.59f, 1205.93f, 9.28f },
            { 1875.83f, 1197.90f, 9.09f },
            { 1876.70f, 1179.83f, 9.49f },
            { 1885.16f, 1171.72f, 9.20f },
            { 1863.49f, 1168.77f, 11.38f },
            { 1857.66f, 1150.46f, 14.95f },
            { 1846.56f, 1136.99f, 19.93f },
            { 1833.76f, 1125.93f, 24.61f },
            { 1820.76f, 1114.49f, 29.29f },
            { 1805.74f, 1104.41f, 34.43f },
            { 1794.54f, 1090.84f, 38.69f },
            { 1781.68f, 1079.46f, 43.16f },
            { 1769.25f, 1068.10f, 46.30f },
            { 1755.58f, 1058.75f, 48.65f },
            { 1745.40f, 1041.43f, 50.32f },
        });
}
