// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 1325400066 (Sacred Pool (Gahz'rilla gong)), 5 anchors over 47yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_1325400066()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 1696.94f, 1195.71f, 10.03f },
            { 1687.21f, 1193.14f, 9.84f },
            { 1695.41f, 1209.64f, 9.60f },
            { 1700.60f, 1216.96f, 9.58f },
            { 1700.98f, 1226.76f, 9.46f },
        });
}
