// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 1325400066 (Altar of Archaedas), 37 anchors over 548yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_1325400066()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 44.15f, 435.41f, -40.49f },
            { 53.00f, 421.99f, -40.49f },
            { 60.28f, 407.51f, -36.85f },
            { 61.59f, 391.45f, -37.69f },
            { 56.61f, 376.16f, -37.62f },
            { 50.77f, 361.09f, -42.50f },
            { 51.20f, 345.05f, -39.75f },
            { 44.98f, 330.43f, -42.68f },
            { 41.39f, 314.38f, -40.24f },
            { 27.95f, 305.51f, -38.61f },
            { 19.31f, 291.94f, -39.37f },
            { 10.68f, 278.36f, -35.75f },
            { 13.40f, 259.10f, -34.86f },
            { 20.64f, 244.71f, -32.25f },
            { 32.04f, 245.22f, -26.37f },
            { 47.76f, 249.43f, -25.99f },
            { 63.35f, 253.75f, -25.99f },
            { 79.00f, 258.05f, -25.97f },
            { 94.89f, 261.69f, -25.70f },
            { 108.76f, 253.89f, -25.61f },
            { 119.29f, 257.67f, -26.09f },
            { 128.13f, 271.16f, -25.92f },
            { 140.77f, 283.14f, -26.04f },
            { 151.57f, 279.71f, -25.95f },
            { 160.34f, 266.52f, -28.06f },
            { 165.31f, 251.08f, -28.79f },
            { 150.90f, 239.22f, -35.28f },
            { 144.26f, 233.67f, -40.69f },
            { 129.78f, 226.51f, -42.33f },
            { 114.57f, 221.03f, -41.89f },
            { 99.45f, 215.39f, -48.26f },
            { 91.83f, 212.71f, -52.24f },
            { 84.18f, 210.20f, -54.39f },
            { 74.98f, 223.47f, -54.97f },
            { 69.45f, 242.37f, -51.82f },
            { 73.93f, 252.94f, -51.69f },
            { 87.04f, 262.31f, -51.57f },
        });
}
