// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7291 (Galgann Firehammer), 11 anchors over 155yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7291()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7291,
        {
            { -38.86f, 275.08f, -47.91f },
            { -22.10f, 278.73f, -46.61f },
            { -14.91f, 287.18f, -46.73f },
            { -25.34f, 300.25f, -45.48f },
            { -28.82f, 307.57f, -43.96f },
            { -27.52f, 315.68f, -40.76f },
            { -11.73f, 322.67f, -39.27f },
            { -10.00f, 339.40f, -39.17f },
            { -4.30f, 360.80f, -42.78f },
            { 0.82f, 378.19f, -43.32f },
            { 1.56f, 397.80f, -45.69f },
        });
}
