// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 62495 (Zel'jeb the Ancient), 22 anchors over 325yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_62495()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 62495,
        {
            { 1700.84f, 1233.98f, 9.49f },
            { 1687.56f, 1244.90f, 9.53f },
            { 1673.99f, 1254.93f, 10.29f },
            { 1666.09f, 1257.89f, 10.28f },
            { 1655.66f, 1273.51f, 9.82f },
            { 1643.16f, 1288.35f, 9.11f },
            { 1626.78f, 1302.33f, 9.81f },
            { 1625.42f, 1311.02f, 9.31f },
            { 1614.95f, 1324.56f, 8.48f },
            { 1611.33f, 1332.03f, 6.54f },
            { 1611.86f, 1340.72f, 3.86f },
            { 1624.25f, 1358.38f, 0.22f },
            { 1636.06f, 1370.44f, -0.02f },
            { 1655.17f, 1376.29f, -0.62f },
            { 1664.84f, 1375.06f, -0.23f },
            { 1668.71f, 1382.45f, -0.91f },
            { 1681.65f, 1392.85f, -0.86f },
            { 1691.98f, 1405.72f, -0.89f },
            { 1703.53f, 1419.75f, -0.95f },
            { 1715.25f, 1431.05f, -0.90f },
            { 1732.28f, 1433.92f, -0.57f },
            { 1750.96f, 1436.21f, -0.24f },
        });
}
