// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 349, boss 12236 (Lord Vyletongue), 52 anchors over 765yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute349_12236()
{
    DungeonClearRouteRegistry::Register(349, DUNGEON_DIFFICULTY_NORMAL, 12236,
        {
            { 978.89f, -10.15f, -62.59f },
            { 973.81f, -28.86f, -62.60f },
            { 970.33f, -45.98f, -62.01f },
            { 956.62f, -54.77f, -61.42f },
            { 939.79f, -58.66f, -61.55f },
            { 922.33f, -61.92f, -59.45f },
            { 906.48f, -73.80f, -59.19f },
            { 907.41f, -96.09f, -60.71f },
            { 909.81f, -115.54f, -61.80f },
            { 907.43f, -136.43f, -60.79f },
            { 906.78f, -156.13f, -60.51f },
            { 910.18f, -172.71f, -59.38f },
            { 912.28f, -181.07f, -57.92f },
            { 910.11f, -190.30f, -55.90f },
            { 902.46f, -196.47f, -52.82f },
            { 889.60f, -212.11f, -52.79f },
            { 876.70f, -221.97f, -54.61f },
            { 858.05f, -229.67f, -54.04f },
            { 850.04f, -232.95f, -54.54f },
            { 845.64f, -250.15f, -55.93f },
            { 828.51f, -248.22f, -59.62f },
            { 809.91f, -246.80f, -60.89f },
            { 801.61f, -244.21f, -62.35f },
            { 799.21f, -235.44f, -63.44f },
            { 782.60f, -229.50f, -66.63f },
            { 774.40f, -213.22f, -65.11f },
            { 768.47f, -205.14f, -65.34f },
            { 768.59f, -196.98f, -62.26f },
            { 769.13f, -188.35f, -59.03f },
            { 774.56f, -171.07f, -56.72f },
            { 773.97f, -152.87f, -56.31f },
            { 762.56f, -140.87f, -56.02f },
            { 748.55f, -129.31f, -56.42f },
            { 735.90f, -118.46f, -56.51f },
            { 724.25f, -106.47f, -56.33f },
            { 707.29f, -98.75f, -55.48f },
            { 700.84f, -104.26f, -56.27f },
            { 683.67f, -105.47f, -55.69f },
            { 666.04f, -108.76f, -56.31f },
            { 649.18f, -108.57f, -56.39f },
            { 640.82f, -109.15f, -56.34f },
            { 627.55f, -122.62f, -54.92f },
            { 622.55f, -140.72f, -54.41f },
            { 626.83f, -147.60f, -53.47f },
            { 637.25f, -148.97f, -51.81f },
            { 644.78f, -146.17f, -51.14f },
            { 645.89f, -157.28f, -52.73f },
            { 660.98f, -164.18f, -51.09f },
            { 676.55f, -171.95f, -48.54f },
            { 686.53f, -171.46f, -48.71f },
            { 687.10f, -181.45f, -48.69f },
            { 694.19f, -187.82f, -47.47f },
        });
}
