// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 6910 (Revelosh), 9 anchors over 114yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_6910()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 6910,
        {
            { -347.53f, 119.68f, -47.89f },
            { -339.81f, 122.67f, -52.56f },
            { -322.57f, 122.82f, -49.52f },
            { -314.52f, 122.65f, -46.77f },
            { -300.62f, 134.44f, -45.35f },
            { -286.18f, 143.42f, -46.67f },
            { -276.34f, 156.85f, -46.89f },
            { -274.83f, 165.23f, -46.89f },
            { -254.34f, 166.72f, -45.61f },
        });
}
