// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 1325400065 (Temple Summit (Executioner event)), 14 anchors over 199yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_1325400065()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 1325400065,
        {
            { 1881.58f, 1021.54f, 9.57f },
            { 1883.52f, 1029.60f, 8.88f },
            { 1872.02f, 1043.21f, 8.88f },
            { 1860.71f, 1055.20f, 9.42f },
            { 1858.09f, 1065.08f, 8.90f },
            { 1865.13f, 1084.37f, 8.88f },
            { 1867.33f, 1101.29f, 9.30f },
            { 1868.56f, 1119.22f, 10.21f },
            { 1869.19f, 1127.63f, 14.41f },
            { 1870.58f, 1146.41f, 11.97f },
            { 1871.80f, 1162.76f, 10.03f },
            { 1873.17f, 1181.39f, 8.88f },
            { 1873.68f, 1198.30f, 8.88f },
            { 1883.66f, 1204.00f, 9.46f },
        });
}
