// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7023 (Obsidian Sentinel), 14 anchors over 185yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7023()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7023,
        {
            { -233.98f, 255.81f, -48.90f },
            { -214.86f, 260.99f, -49.12f },
            { -199.67f, 268.76f, -48.03f },
            { -198.63f, 277.15f, -45.86f },
            { -185.42f, 288.00f, -47.74f },
            { -181.30f, 295.53f, -50.44f },
            { -181.76f, 304.83f, -51.88f },
            { -166.40f, 319.95f, -50.72f },
            { -149.95f, 319.03f, -47.32f },
            { -139.86f, 326.27f, -43.85f },
            { -127.59f, 339.72f, -42.76f },
            { -123.51f, 347.31f, -43.13f },
            { -123.54f, 356.20f, -43.43f },
            { -134.73f, 371.27f, -40.69f },
        });
}
