// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 62498 (Champion Razjal the Quick), 36 anchors over 571yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_62498()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 62498,
        {
            { 1758.70f, 1435.32f, 0.43f },
            { 1742.06f, 1433.67f, -0.56f },
            { 1725.48f, 1432.82f, -0.67f },
            { 1709.85f, 1428.27f, -1.00f },
            { 1700.04f, 1414.91f, -0.95f },
            { 1688.78f, 1402.74f, -0.83f },
            { 1678.22f, 1389.72f, -0.80f },
            { 1668.20f, 1375.83f, -1.07f },
            { 1657.71f, 1361.44f, -0.60f },
            { 1643.09f, 1354.29f, -0.18f },
            { 1626.61f, 1351.65f, 0.21f },
            { 1618.27f, 1349.57f, 0.59f },
            { 1611.80f, 1343.59f, 2.91f },
            { 1611.71f, 1331.64f, 6.71f },
            { 1617.42f, 1316.20f, 9.41f },
            { 1623.86f, 1300.72f, 9.28f },
            { 1636.55f, 1289.21f, 9.15f },
            { 1648.07f, 1276.27f, 9.62f },
            { 1658.16f, 1262.15f, 9.93f },
            { 1652.59f, 1245.41f, 14.25f },
            { 1647.58f, 1229.15f, 10.58f },
            { 1642.01f, 1213.46f, 9.87f },
            { 1638.89f, 1196.59f, 8.96f },
            { 1635.15f, 1180.09f, 9.15f },
            { 1632.79f, 1163.57f, 8.90f },
            { 1630.23f, 1147.02f, 8.88f },
            { 1618.27f, 1133.66f, 8.88f },
            { 1603.66f, 1119.58f, 8.88f },
            { 1591.02f, 1107.94f, 9.68f },
            { 1585.71f, 1100.43f, 10.83f },
            { 1582.20f, 1084.13f, 9.66f },
            { 1568.64f, 1070.27f, 8.88f },
            { 1558.33f, 1054.92f, 9.17f },
            { 1554.53f, 1037.54f, 11.71f },
            { 1539.23f, 1030.73f, 11.69f },
            { 1523.46f, 1025.20f, 11.58f },
        });
}
