// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7228 (Ironaya), 5 anchors over 60yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7228()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7228,
        {
            { -223.75f, 161.78f, -44.00f },
            { -229.97f, 180.15f, -44.07f },
            { -231.24f, 196.42f, -44.17f },
            { -231.77f, 213.03f, -45.35f },
            { -232.54f, 221.31f, -45.98f },
        });
}
