// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 349, boss 12225 (Celebras the Cursed), 41 anchors over 712yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute349_12225()
{
    DungeonClearRouteRegistry::Register(349, DUNGEON_DIFFICULTY_NORMAL, 12225,
        {
            { 696.36f, -183.63f, -47.07f },
            { 689.54f, -166.54f, -48.76f },
            { 681.39f, -149.30f, -48.67f },
            { 662.50f, -147.14f, -50.60f },
            { 642.70f, -149.04f, -52.03f },
            { 625.76f, -145.54f, -53.58f },
            { 622.66f, -138.15f, -54.59f },
            { 630.29f, -123.39f, -55.67f },
            { 639.12f, -109.74f, -56.28f },
            { 656.08f, -107.06f, -56.39f },
            { 672.38f, -101.24f, -57.50f },
            { 688.96f, -100.35f, -56.01f },
            { 705.70f, -102.64f, -56.25f },
            { 724.72f, -106.25f, -56.36f },
            { 739.73f, -114.80f, -56.63f },
            { 756.96f, -123.04f, -56.46f },
            { 765.10f, -127.26f, -56.39f },
            { 772.17f, -145.67f, -56.28f },
            { 776.33f, -163.53f, -56.20f },
            { 771.27f, -180.12f, -57.73f },
            { 768.57f, -197.61f, -62.54f },
            { 773.33f, -204.45f, -66.89f },
            { 786.92f, -193.12f, -72.31f },
            { 794.61f, -193.79f, -76.82f },
            { 817.65f, -193.14f, -74.86f },
            { 854.77f, -152.11f, -89.38f },
            { 849.65f, -135.19f, -87.86f },
            { 844.23f, -118.78f, -87.85f },
            { 838.54f, -100.75f, -88.03f },
            { 831.91f, -81.56f, -87.36f },
            { 823.59f, -65.84f, -87.95f },
            { 817.61f, -50.23f, -88.00f },
            { 811.94f, -31.02f, -87.72f },
            { 808.75f, -14.93f, -87.77f },
            { 804.64f, 1.72f, -87.80f },
            { 799.03f, 18.68f, -87.63f },
            { 786.92f, 33.68f, -87.63f },
            { 773.26f, 45.86f, -87.63f },
            { 760.66f, 57.27f, -87.63f },
            { 748.47f, 68.22f, -88.25f },
            { 740.92f, 71.87f, -86.89f },
        });
}
