// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 349, boss 12258 (Razorlash), 25 anchors over 374yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute349_12258()
{
    DungeonClearRouteRegistry::Register(349, DUNGEON_DIFFICULTY_NORMAL, 12258,
        {
            { 1104.04f, -241.80f, -75.85f },
            { 1089.48f, -253.04f, -73.13f },
            { 1076.19f, -263.29f, -72.07f },
            { 1068.66f, -266.38f, -72.46f },
            { 1052.60f, -260.40f, -73.07f },
            { 1044.80f, -257.13f, -72.20f },
            { 1037.22f, -239.68f, -71.70f },
            { 1028.53f, -222.56f, -71.04f },
            { 1019.68f, -208.74f, -67.92f },
            { 1006.48f, -195.76f, -67.08f },
            { 990.38f, -185.21f, -67.74f },
            { 972.68f, -180.51f, -66.46f },
            { 956.44f, -176.13f, -63.98f },
            { 948.30f, -174.28f, -63.20f },
            { 943.70f, -164.67f, -60.03f },
            { 953.64f, -160.90f, -58.54f },
            { 949.72f, -150.37f, -59.95f },
            { 954.51f, -130.55f, -61.19f },
            { 959.22f, -113.52f, -62.61f },
            { 959.70f, -94.31f, -62.60f },
            { 963.90f, -77.48f, -61.34f },
            { 968.18f, -58.48f, -61.37f },
            { 972.04f, -42.21f, -61.74f },
            { 975.74f, -24.90f, -62.37f },
            { 977.57f, -16.33f, -62.59f },
        });
}
