// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 6906 (Baelog), 14 anchors over 190yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_6906()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 6906,
        {
            { -226.80f, 49.09f, -46.03f },
            { -242.09f, 56.52f, -45.49f },
            { -258.16f, 60.41f, -47.89f },
            { -276.45f, 69.22f, -48.52f },
            { -281.03f, 85.45f, -48.46f },
            { -262.20f, 90.60f, -48.20f },
            { -253.92f, 93.14f, -48.10f },
            { -246.33f, 104.52f, -48.09f },
            { -249.82f, 122.38f, -46.45f },
            { -249.77f, 130.91f, -46.19f },
            { -256.30f, 136.21f, -46.60f },
            { -272.77f, 137.64f, -46.87f },
            { -290.76f, 138.36f, -46.16f },
            { -299.40f, 137.37f, -45.29f },
        });
}
