// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 1325400067 (Farraki Arena (Razjal's challenge)), 5 anchors over 51yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_1325400067()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 1325400067,
        {
            { 1504.80f, 1005.01f, 12.22f },
            { 1505.51f, 1019.05f, 12.10f },
            { 1511.38f, 1026.92f, 12.12f },
            { 1493.02f, 1026.86f, 12.27f },
            { 1484.09f, 1024.90f, 12.68f },
        });
}
