// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 7272 (Theka the Martyr), 45 anchors over 569yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_7272()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 7272,
        {
            { 1213.52f, 841.59f, 8.93f },
            { 1233.74f, 843.28f, 9.63f },
            { 1252.15f, 843.05f, 9.71f },
            { 1267.82f, 838.36f, 9.66f },
            { 1279.53f, 826.38f, 9.50f },
            { 1290.66f, 824.73f, 9.68f },
            { 1306.71f, 826.58f, 11.58f },
            { 1327.18f, 823.87f, 10.31f },
            { 1343.74f, 820.83f, 9.66f },
            { 1360.46f, 817.74f, 9.59f },
            { 1376.82f, 814.55f, 9.62f },
            { 1395.22f, 809.84f, 9.80f },
            { 1411.08f, 805.26f, 9.59f },
            { 1428.90f, 796.79f, 12.01f },
            { 1447.29f, 798.61f, 18.73f },
            { 1463.25f, 804.13f, 12.32f },
            { 1478.83f, 810.42f, 9.52f },
            { 1495.53f, 806.92f, 9.43f },
            { 1503.31f, 809.92f, 9.43f },
            { 1508.21f, 816.73f, 9.43f },
            { 1525.58f, 820.38f, 9.55f },
            { 1536.97f, 809.29f, 16.75f },
            { 1544.73f, 806.05f, 22.57f },
            { 1548.84f, 806.41f, 27.21f },
            { 1557.71f, 808.37f, 31.57f },
            { 1566.15f, 808.36f, 38.37f },
            { 1570.16f, 808.26f, 43.73f },
            { 1574.15f, 807.97f, 48.97f },
            { 1578.53f, 806.70f, 53.19f },
            { 1586.58f, 804.85f, 48.61f },
            { 1590.82f, 805.75f, 43.84f },
            { 1595.15f, 805.97f, 36.31f },
            { 1599.36f, 805.67f, 29.51f },
            { 1603.63f, 805.29f, 24.40f },
            { 1607.83f, 804.90f, 20.37f },
            { 1616.61f, 804.09f, 13.01f },
            { 1624.92f, 803.32f, 8.92f },
            { 1641.33f, 800.49f, 9.05f },
            { 1650.07f, 794.94f, 8.88f },
            { 1667.88f, 795.26f, 11.07f },
            { 1683.76f, 801.17f, 9.85f },
            { 1699.45f, 808.91f, 9.63f },
            { 1717.50f, 817.54f, 8.88f },
            { 1732.83f, 824.43f, 9.84f },
            { 1749.92f, 832.25f, 10.00f },
        });
}
