// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 7795 (Hydromancer Velratha), 15 anchors over 106yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_7795()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 7795,
        {
            { 1723.83f, 1085.43f, 64.95f },
            { 1727.30f, 1088.95f, 69.24f },
            { 1728.06f, 1098.17f, 65.23f },
            { 1728.05f, 1102.34f, 59.46f },
            { 1727.96f, 1106.83f, 53.62f },
            { 1720.94f, 1112.68f, 44.47f },
            { 1717.44f, 1114.78f, 37.97f },
            { 1713.62f, 1116.35f, 32.14f },
            { 1709.75f, 1117.75f, 27.10f },
            { 1705.12f, 1119.55f, 20.48f },
            { 1701.29f, 1121.58f, 15.42f },
            { 1695.03f, 1127.54f, 11.46f },
            { 1688.18f, 1142.16f, 9.43f },
            { 1677.09f, 1158.33f, 9.12f },
            { 1672.93f, 1165.45f, 9.48f },
        });
}
