// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 349, boss 13282 (Noxxion), 49 anchors over 714yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute349_13282()
{
    DungeonClearRouteRegistry::Register(349, DUNGEON_DIFFICULTY_NORMAL, 13282,
        {
            { 1019.69f, -458.31f, -43.43f },
            { 1024.98f, -450.93f, -42.69f },
            { 1044.79f, -447.98f, -42.24f },
            { 1062.73f, -450.58f, -42.12f },
            { 1071.45f, -452.07f, -42.06f },
            { 1073.63f, -456.80f, -37.42f },
            { 1066.28f, -458.93f, -31.22f },
            { 1062.91f, -440.17f, -30.98f },
            { 1061.10f, -422.55f, -31.74f },
            { 1057.10f, -406.52f, -33.52f },
            { 1047.90f, -385.42f, -35.69f },
            { 1031.11f, -384.04f, -35.69f },
            { 1019.31f, -369.76f, -37.81f },
            { 1008.19f, -354.30f, -40.67f },
            { 1000.59f, -335.53f, -42.19f },
            { 990.32f, -316.16f, -44.90f },
            { 980.60f, -299.70f, -45.05f },
            { 968.06f, -285.31f, -45.03f },
            { 960.93f, -280.24f, -45.07f },
            { 956.08f, -271.03f, -45.06f },
            { 938.89f, -260.15f, -45.26f },
            { 923.02f, -254.89f, -45.93f },
            { 900.40f, -263.60f, -45.98f },
            { 894.16f, -269.51f, -45.16f },
            { 896.33f, -286.56f, -45.48f },
            { 899.13f, -304.69f, -46.51f },
            { 907.58f, -320.44f, -49.55f },
            { 916.73f, -326.32f, -49.19f },
            { 927.21f, -338.99f, -49.29f },
            { 943.98f, -351.14f, -50.24f },
            { 957.82f, -360.73f, -49.93f },
            { 964.90f, -365.30f, -49.79f },
            { 973.81f, -366.43f, -50.03f },
            { 986.32f, -354.63f, -52.31f },
            { 990.83f, -347.41f, -55.78f },
            { 994.79f, -340.28f, -60.10f },
            { 998.36f, -332.49f, -64.20f },
            { 1003.34f, -325.77f, -67.37f },
            { 1016.27f, -313.60f, -71.31f },
            { 1033.52f, -307.55f, -71.71f },
            { 1050.44f, -309.73f, -72.51f },
            { 1060.12f, -308.79f, -72.52f },
            { 1073.29f, -295.00f, -72.09f },
            { 1072.00f, -285.42f, -72.10f },
            { 1074.80f, -277.50f, -71.90f },
            { 1086.13f, -279.57f, -72.04f },
            { 1092.52f, -259.94f, -73.15f },
            { 1100.32f, -258.06f, -74.92f },
            { 1110.45f, -242.13f, -77.07f },
        });
}
