// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 7271 (Witch Doctor Zum'rah), 19 anchors over 271yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_7271()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 7271,
        {
            { 1809.83f, 713.03f, 15.98f },
            { 1806.98f, 730.01f, 15.41f },
            { 1805.26f, 746.79f, 16.23f },
            { 1807.99f, 762.77f, 22.64f },
            { 1808.02f, 773.01f, 18.90f },
            { 1808.03f, 789.53f, 18.10f },
            { 1809.19f, 797.87f, 14.61f },
            { 1813.11f, 814.32f, 12.40f },
            { 1816.81f, 831.11f, 9.53f },
            { 1818.04f, 847.47f, 9.54f },
            { 1819.72f, 864.43f, 9.48f },
            { 1821.01f, 872.76f, 9.47f },
            { 1825.92f, 879.52f, 9.61f },
            { 1820.85f, 895.57f, 9.48f },
            { 1820.48f, 904.22f, 9.43f },
            { 1829.44f, 921.96f, 9.45f },
            { 1840.72f, 939.55f, 9.70f },
            { 1849.87f, 953.97f, 9.54f },
            { 1860.27f, 969.24f, 9.84f },
        });
}
