// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 8127 (Antu'sul), 10 anchors over 129yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_8127()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 8127,
        {
            { 1772.36f, 853.48f, 9.63f },
            { 1788.21f, 849.13f, 9.57f },
            { 1799.43f, 836.33f, 9.58f },
            { 1810.51f, 821.14f, 10.82f },
            { 1811.71f, 812.73f, 14.08f },
            { 1808.41f, 795.29f, 15.60f },
            { 1807.30f, 786.61f, 18.72f },
            { 1805.08f, 770.44f, 17.20f },
            { 1804.01f, 753.08f, 17.52f },
            { 1804.07f, 744.70f, 15.57f },
        });
}
