// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7206 (Ancient Stone Keeper), 21 anchors over 289yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7206()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7206,
        {
            { -151.11f, 384.07f, -38.25f },
            { -137.06f, 372.89f, -40.45f },
            { -124.02f, 362.03f, -43.09f },
            { -108.80f, 355.03f, -46.04f },
            { -91.77f, 353.40f, -48.39f },
            { -75.26f, 357.91f, -50.69f },
            { -60.80f, 365.08f, -48.48f },
            { -44.05f, 358.06f, -46.77f },
            { -28.00f, 349.65f, -42.95f },
            { -13.83f, 340.08f, -39.83f },
            { 0.88f, 331.51f, -38.39f },
            { 9.08f, 330.45f, -38.12f },
            { 3.41f, 322.38f, -37.57f },
            { -14.44f, 319.61f, -38.88f },
            { -23.35f, 318.23f, -39.24f },
            { -28.74f, 307.89f, -43.85f },
            { -18.42f, 292.69f, -46.83f },
            { -14.67f, 284.59f, -47.38f },
            { -19.41f, 278.13f, -46.64f },
            { -34.74f, 271.37f, -48.06f },
            { -37.86f, 263.83f, -48.42f },
        });
}
