// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 4854 (Grimlok), 11 anchors over 154yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_4854()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 4854,
        {
            { 9.37f, 397.28f, -44.00f },
            { 2.39f, 389.66f, -43.49f },
            { 1.71f, 372.74f, -42.74f },
            { 8.12f, 366.91f, -41.89f },
            { 27.42f, 368.10f, -39.86f },
            { 44.53f, 376.96f, -36.56f },
            { 61.24f, 378.93f, -38.14f },
            { 61.31f, 395.83f, -37.64f },
            { 63.60f, 405.94f, -37.71f },
            { 53.49f, 422.33f, -40.46f },
            { 41.47f, 433.23f, -40.84f },
        });
}
